export const exceptionStatus = [
  '',
  'Approved By Lender',
  'Approved By Investor',
  'Denied By Lender',
  'Denied By Investor',
  'Waived - Not Required',
  'Pending With Lender',
  'Pending With Investor',
]

export const docStatus = [
  'Not Reviewed',
  'Approved',
  'Inactive',
  'Incomplete',
  'Missing Pages',
  'Unacceptable',
  'Duplicate',
  'Illegible',
  'Reviewed',
]

export const docCategory = [
  ' ',
  'Appraisal Docs',
  'Assets',
  'AUS',
  'CD REQUEST',
  'CLOSING PACKAGE',
  'CLOSING REQUEST',
  'Credit Report',
  'Disclosures',
  'Flood/IRS transcripts',
  'GOV',
  'HOI/HO6',
  `ID's`,
  'Income',
  'INVOICES',
  'JUNK',
  'LE/CD - Compliance',
  'LOCK',
  `MISC / VOE's`,
  'POST CLOSING CONDITIONS',
  'Property Docs',
  'TITLE Docs',
  'TRAILING DOCS',
  'UW MISC',
  'UW PACKAGE',
  'WIRE REQUEST',
]
