import type { InputType } from './input.type.constants'

export const loanOptionsConstants = {
  purpose: [
    [
      'Commercial Bridge',
      'SFR Bridge',
      'Commercial Rehab and Construction',
      'Residential Construction & Fix and Flip',
      'Residential DSCR',
      'Commercial DSCR',
    ],
    [
      'Commercial Bridge',
      'SFR Bridge',
      'Commercial Rehab and Construction',
      'Residential Construction & Fix and Flip',
      'Residential DSCR',
      'Commercial DSCR',
    ],
  ],
  loanTerm: {
    12: '12 months',
    18: '18 months',
    24: '24 months',
  },
  borrowerType: ['LLC', 'LLP', 'Corp', 'S Corp', 'Partnership', 'Revocable Trust', 'Irrevocable Trust', 'Individual'],
  prepaymentLong: ['0 years', '1 years', '2 years', '3 years', '4 years', '5 years'],
  prepaymentShort: {
    36: '3 years',
  },
  propertyType: [
    ['SFR', 'Condo', '2-4 Units', 'PUD', '5-9 Units', '10+ Units', 'Mixed-Use', 'Land', 'Other'],
    ['SFR', 'Condo', '2-4 Units', 'PUD', 'Mixed-Use'],
    ['SFR', 'Condo', '2-4 Units', 'PUD'],
    ['SFR', 'Condo', '2-4 Units'],
  ],
  propertyTypeSmallList: ['Mixed-Use', 'MF (5-30 units)', 'Industrial', 'MHP', 'Self Storage', 'Office', 'Retail'],
  propertyTypeBigList: [
    'SFR',
    'Condo',
    '2-4 Units',
    'PUD',
    'Mixed-Use',
    'MF (5-30 units)',
    'Industrial',
    'MHP',
    'Self Storage',
    'Office',
    'Retail',
  ],
  additionalPropertyType: ['MF (5-30 units)', 'Industrial', 'MHP', 'Self Storage', 'Office', 'Retail'],
  loannex1: ['None', 'Not Settled (<12)', 'Settled (<12)', '1+ years'],
  loannex2: ['None', '2+ years', '3+ years', '4+ years'],
}

export const initialLoanFields: { [key: string]: InputType } = {
  productType: {
    title: 'Product Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: [
      'Commercial Bridge',
      'SFR Bridge',
      'Commercial Rehab and Construction',
      'Residential Construction & Fix and Flip',
      'Residential DSCR',
      'Commercial DSCR',
    ],
    error: '',
    required: true,
  },
  transactionType: {
    title: 'Transaction Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['Purchase', 'Refinance'],
    error: '',
    required: true,
  },
  proposedOccupancy: {
    title: 'Proposed Occupancy',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['Owner Occupied', 'Non Owner Occupied', 'Partially Owner Occupied'],
    error: '',
    required: true,
  },
  currentCoeDate: {
    inputType: 'text',
    title: 'Current COE Date',
    type: 'date',
  },
  loanTerm: {
    title: 'Loan Term',
    inputType: 'select',
    hasDefaultOption: true,
    options: loanOptionsConstants.loanTerm,
    error: '',
    required: true,
  },
  borrowerType: {
    title: 'Borrower Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: loanOptionsConstants.borrowerType,
    error: '',
    required: true,
  },
  proposedLoanAmount: {
    title: 'Proposed Loan Amount',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  propertyPurchasePrice: {
    title: 'Property Purchase Price',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  asIsValue: {
    title: 'As Is Value',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  afterRepairValue: {
    title: 'After Repair Value',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  rehabBudget: {
    title: 'Rehab Budget',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  constructionReserve: {
    title: 'Construction Reserve',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  cashOutAmount: {
    title: 'Cash Out Amount',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  experience: {
    title: 'Experience',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['0 Transaction', '1 Transaction', '2 Transactions', '3+ Transactions'],
    error: '',
    required: true,
  },
  proposedMonthlyTaxes: {
    title: 'Proposed Monthly Taxes',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  proposedMonthlyInsurance: {
    title: 'Proposed Monthly Insurance',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  proposedMonthlyRent: {
    title: 'Proposed Monthly Rent',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  proposedMonthlyHoaDues: {
    title: 'Proposed Monthly HOA Dues',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  propertyType: {
    title: 'Property Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: loanOptionsConstants.propertyTypeSmallList,
    error: '',
    required: true,
  },
  condoType: {
    title: 'Condo Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['Warrantable', 'Non-Warrantable', 'Condotel'],
    error: '',
    required: true,
  },
  prepaymentPenalty: {
    title: 'Prepayment Penalty',
    inputType: 'select',
    hasDefaultOption: true,
    value: 36,
    options: loanOptionsConstants.prepaymentLong,
    error: '',
    required: true,
  },
  residency: {
    title: 'Residency',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['US Citizen', 'Permanent Resident', 'Non Permanent Resident', 'Foreign National'],
    error: '',
    required: true,
  },
  amortizationType: {
    title: 'Amortization Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['Fully Amortized', '10 Year Interest Only'],
    error: '',
    required: true,
  },
  escrowType: {
    title: 'Escrow Type',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['Not Waived', 'Waive Both'],
    error: '',
    required: true,
  },
  countryOfCreditScore: {
    title: 'Country of Credit Score',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['US Credit', 'Foreign Credit'],
    error: '',
    required: true,
  },
  selfEmployed: {
    title: 'Self Employed?',
    inputType: 'check',
    value: false,
    error: '',
    required: true,
  },
  firstTimeHomeBuyer: {
    title: 'First Time Homebuyer?',
    inputType: 'check',
    error: '',
    required: true,
  },
  firstTimeHomeInvestor: {
    title: 'First Time Home Investor?',
    inputType: 'check',
    error: '',
    required: true,
  },
  ruralProperty: {
    title: 'Rural Property?',
    inputType: 'check',
    error: '',
    required: true,
  },
  bankruptcy: {
    title: 'Bankruptcy',
    inputType: 'select',
    hasDefaultOption: true,
    options: [...loanOptionsConstants.loannex1],
    error: '',
    required: true,
  },
  foreclosure: {
    title: 'Foreclosure',
    inputType: 'select',
    hasDefaultOption: true,
    options: [...loanOptionsConstants.loannex2],
    error: '',
    required: true,
  },
  deedInLieu: {
    title: 'Deed-In-Lieu',
    inputType: 'select',
    hasDefaultOption: true,
    options: [...loanOptionsConstants.loannex2],
    error: '',
    required: true,
  },
  shortSale: {
    title: 'Short Sale',
    inputType: 'select',
    hasDefaultOption: true,
    options: [...loanOptionsConstants.loannex2],
    error: '',
    required: true,
  },
  mortgageLates: {
    title: 'Mortgage Lates',
    inputType: 'select',
    hasDefaultOption: true,
    options: ['0X30X12', '= 1X30X12', '> 1X30X12', '>= 1X60X12'],
    error: '',
    required: true,
  },
  secondLien: {
    title: 'Second Lien',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  monthsReserve: {
    title: 'Months Reserve',
    inputType: 'text',
    type: 'number',
    error: '',
    required: true,
  },
  estimatedDscr: {
    title: 'Estimated DSCR',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '%',
    required: true,
  },
  numberOfUnits: {
    title: 'Number of Units',
    inputType: 'text',
    type: 'number',
    error: '',
    required: true,
  },
  cashInHand: {
    title: 'Cash in Hand',
    inputType: 'text',
    type: 'thousandSep',
    error: '',
    prefix: '$',
    required: true,
  },
  guarantorFirstName: {
    title: 'Guarantor First Name',
    inputType: 'text',
    error: '',
  },
  guarantorLastName: {
    title: 'Guarantor Last Name',
    inputType: 'text',
    error: '',
    required: false,
  },
  borrowerFirstName: {
    title: 'Borrower First Name',
    inputType: 'text',
    error: '',
    required: true,
  },
  borrowerMiddleName: {
    title: 'Borrower Middle Name',
    inputType: 'text',
    error: '',
  },
  borrowerLastName: {
    title: 'Borrower Last Name',
    inputType: 'text',
    error: '',
    required: true,
  },
  estimatedCreditScore: {
    title: 'Estimated Credit Score',
    inputType: 'text',
    type: 'number',
    error: '',
    required: true,
  },
  subjectPropertyAddress: {
    title: 'Subject Property Address',
    inputType: 'Map',
    error: '',
    required: true,
  },
}

export const fieldsByTransactionTypeAndProductTypeConstant: { [key: string]: { [key1: string]: string[] } } = {
  'Commercial Bridge': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'loanTerm',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'experience',
      'propertyType',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'loanTerm',
      'borrowerType',
      'proposedLoanAmount',
      'asIsValue',
      'experience',
      'propertyType',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
  },
  'SFR Bridge': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'experience',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'borrowerType',
      'proposedLoanAmount',
      'asIsValue',
      'experience',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
      'proposedOccupancy',
    ],
  },
  'Commercial Rehab and Construction': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'experience',
      'afterRepairValue',
      'rehabBudget',
      'constructionReserve',
      'propertyType',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'borrowerType',
      'proposedLoanAmount',
      'asIsValue',
      'cashOutAmount',
      'experience',
      'afterRepairValue',
      'constructionReserve',
      'propertyType',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
  },
  'Residential Construction & Fix and Flip': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'experience',
      'afterRepairValue',
      'rehabBudget',
      'constructionReserve',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'currentCoeDate',
      'proposedLoanAmount',
      'asIsValue',
      'cashOutAmount',
      'experience',
      'afterRepairValue',
      'rehabBudget',
      'constructionReserve',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
  },
  'Residential DSCR': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'propertyType',
      'prepaymentPenalty',
      'residency',
      'amortizationType',
      'escrowType',
      'selfEmployed',
      'firstTimeHomeBuyer',
      'ruralProperty',
      'bankruptcy',
      'foreclosure',
      'deedInLieu',
      'shortSale',
      'mortgageLates',
      'secondLien',
      'monthsReserve',
      'estimatedDscr',
      'numberOfUnits',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'borrowerType',
      'proposedLoanAmount',
      'asIsValue',
      'cashOutAmount',
      'propertyType',
      'prepaymentPenalty',
      'residency',
      'amortizationType',
      'escrowType',
      'selfEmployed',
      'firstTimeHomeBuyer',
      'ruralProperty',
      'bankruptcy',
      'foreclosure',
      'deedInLieu',
      'shortSale',
      'mortgageLates',
      'secondLien',
      'monthsReserve',
      'estimatedDscr',
      'numberOfUnits',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
  },
  'Commercial DSCR': {
    Purchase: [
      'proposedOccupancy',
      'currentCoeDate',
      'borrowerType',
      'proposedLoanAmount',
      'propertyPurchasePrice',
      'asIsValue',
      'propertyType',
      'prepaymentPenalty',
      'residency',
      'amortizationType',
      'escrowType',
      'selfEmployed',
      'firstTimeHomeBuyer',
      'ruralProperty',
      'bankruptcy',
      'foreclosure',
      'deedInLieu',
      'shortSale',
      'mortgageLates',
      'secondLien',
      'monthsReserve',
      'estimatedDscr',
      'numberOfUnits',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
    Refinance: [
      'proposedOccupancy',
      'borrowerType',
      'proposedLoanAmount',
      'asIsValue',
      'cashOutAmount',
      'propertyType',
      'prepaymentPenalty',
      'residency',
      'amortizationType',
      'escrowType',
      'selfEmployed',
      'firstTimeHomeBuyer',
      'ruralProperty',
      'bankruptcy',
      'foreclosure',
      'deedInLieu',
      'shortSale',
      'mortgageLates',
      'secondLien',
      'monthsReserve',
      'estimatedDscr',
      'numberOfUnits',
      'guarantorFirstName',
      'guarantorLastName',
      'borrowerFirstName',
      'borrowerMiddleName',
      'borrowerLastName',
      'estimatedCreditScore',
      'subjectPropertyAddress',
    ],
  },
}

export const groupedFields = [
  ['productType', 'transactionType'],
  ['proposedOccupancy', 'prepaymentPenalty'],
  ['currentCoeDate', 'loanTerm', 'experience'],
  ['amortizationType', 'escrowType'],
  ['residency', 'countryOfCreditScore', 'estimatedCreditScore'],
  [
    'proposedLoanAmount',
    'propertyPurchasePrice',
    'asIsValue',
    'afterRepairValue',
    'rehabBudget',
    'constructionReserve',
  ],
  ['cashInHand', 'cashOutAmount'],
  ['proposedMonthlyTaxes', 'proposedMonthlyInsurance', 'proposedMonthlyRent', 'proposedMonthlyHoaDues'],
  ['propertyType', 'numberOfUnits', 'condoType'],
  ['selfEmployed', 'firstTimeHomeBuyer', 'firstTimeHomeInvestor', 'ruralProperty'],
  ['bankruptcy', 'foreclosure', 'deedInLieu', 'shortSale', 'mortgageLates'],
  [
    'guarantorFirstName',
    'guarantorLastName',
    'borrowerType',
    'borrowerFirstName',
    'borrowerMiddleName',
    'borrowerLastName',
  ],
  ['secondLien', 'monthsReserve', 'estimatedDscr'],
  ['subjectPropertyAddress'],
]

export const OwnershipTypes = {
  own: 'Own',
  rent: 'Rent',
}

export const YesNoOptions = {
  yes: 'Yes',
  no: 'No',
}

export const YearOptions = {
  '1': '1 year',
  '2': '2 years',
  '3': '3 years',
  '4': '4 years',
  '5': '5 years',
  '6': '6 years',
  '7': '7 years',
  '8': '8 years',
  '9': '9 years',
  '10': '10+ years',
}

export const MaritalStatusTypes = {
  married: 'Married (includes registered domestic partners)',
  unmarried: 'Unmarried (includes divorced, widow)',
  single: 'Single (never been married)',
  separated: 'Separated',
}

export const priceLoanRelatedFields = [
  'transactionType',
  'productType',
  'proposedOccupancy',
  'proposedLoanAmount',
  'propertyPurchasePrice',
  'asIsValue',
  'afterRepairValue',
  'rehabBudget',
  'constructionReserve',
  'countryOfCreditScore',
  'cashOutAmount',
  'cashInHand',
  'escrowType',
  'propertyType',
  'numberOfUnits',
  'selfEmployed',
  'firstTimeHomeBuyer',
  'firstTimeHomeInvestor',
  'ruralProperty',
  'bankruptcy',
  'foreclosure',
  'deedInLieu',
  'shortSale',
  'mortgageLates',
  'secondLien',
  'monthsReserve',
  'estimatedDscr',
  'numberOfUnits',
  'cashInHand',
  'propertyType',
  'condoType',
  'prepaymentPenalty',
  'residency',
  'amortizationType',
  'subjectPropertyAddress',
  'estimatedCreditScore',
  'experience',
]

export const priceLimitRelatedFields = [
  'transactionType',
  'estimatedCreditScore',
  'productType',
  'proposedLoanAmount',
  'propertyPurchasePrice',
  'asIsValue',
  'afterRepairValue',
  'rehabBudget',
  'constructionReserve',
  'experience',
  'countryOfCreditScore',
]
