export const loanStatusConstants = {
  closeStatus: ['Clear to Close', 'Ready for Docs', 'Docs Out', 'Closed', 'Funded', 'Withdrawn'],
  status: [
    'Prequal',
    'Application',
    'Submitted',
    'Suspended',
    'Approved',
    'Resubmitted',
    'AM Review',
    'Underwriter Review',
    'Declined',
    'Clear to Close',
    'Ready for Docs',
    'Docs Out',
    'Closed',
    'Funded',
    'Withdrawn',
  ],
}
