export const Permissions = {
  MANAGE_VENDORS: 'MANAGE_VENDORS',
  MANAGE_CONDITIONS_TEMPLATES: 'MANAGE_CONDITIONS_TEMPLATES',
  MANAGE_DEFAULTS: 'MANAGE_DEFAULTS',
  MANAGE_ADMIN_TOOLS: 'MANAGE_ADMIN_TOOLS',
  MANAGE_USER_ACTIVITY: 'MANAGE_USER_ACTIVITY',
  MANAGE_ACCOUNTS: 'MANAGE_ACCOUNTS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  ACCOUNT_SYSTEM_VIEW: 'ACCOUNT_SYSTEM_VIEW',
}
